### ISSUE TITLE
DataConversionWarning: column-vector passed when 1d array expected

### ISSUE THREAD

**Issue by stsievert** [adriangb/scikeras#19]
I'm having difficulty figuring this error out. Here's the setup:

* I have a script that uses `keras.datasets.mnist`. It reshapes into a 2D array and a 1D vector of labels:

``` python
import tensorflow as tf
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import mnist
from scikeras.wrappers import KerasClassifier

def get_keras():
    (X_train, y_train), _ = mnist.load_data()
    X_train, y_train = X_train[:100], y_train[:100]
    X_train = X_train.reshape(X_train.shape[0], 784).astype("float32") / 255
    return X_train, y_train

def _keras_build_fn(opt="sgd"):
    model = Sequential([Dense(512, input_shape=(784,)), Activation("relu"),
                        Dense(10), Activation("softmax")])
    model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["accuracy"])
    return model

def test_keras():
    X, y = get_keras()
    assert X.ndim == 2 and X.shape[-1] == 784 and y.ndim == 1
    model = KerasClassifier(build_fn=_keras_build_fn)
    model.fit(X, y)

if __name__ == "__main__":
    test_keras()
```

* I run this script with `python _scikeras_bug.py`. Everything works.
* I run this script with `pytest _scikeras_bug.py`, and I get this error:

> sklearn.exceptions.DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Here's the traceback:

```
_scikeras_bug.py:36:
    model.fit(X, y)
../scikeras/scikeras/wrappers.py:503: in fit
    y, extra_args = self._pre_process_y(y)
../scikeras/scikeras/wrappers.py:742: in _pre_process_y
    y = encoder.fit_transform(y)
../../../anaconda3/envs/dask-ml-docs/lib/python3.6/site-packages/sklearn/preprocessing/_label.py:255: in fit_transform
    y = column_or_1d(y, warn=True)
../../../anaconda3/envs/dask-ml-docs/lib/python3.6/site-packages/sklearn/utils/validation.py:73: in inner_f
    return f(**kwargs)../../../anaconda3/envs/dask-ml-docs/lib/python3.6/site-packages/sklearn/utils/validation.py:843: DataConversionWarning
```

I've tried this out with two environments, and got the same error both times:

* pytest 5.4.3, scikeras 0.1.7, Tensorflow 2.2.0, Python 3.6.10
* pytest 6.0.0rc1, scikeras 0.1.7, Tensorflow 2.2.0, Python 3.8.3.

**Comment by adriangb** [comment]
This is very strange. AFAIK, pytest should behave the same as Python. I tested under your second env (pytest 6.0.0rc1, scikeras 0.1.7, Tensorflow 2.2.0, Python 3.8.3) locally and could not reproduce. I also tested in a collab notebook ([link](https://colab.research.google.com/drive/1OcnYieYJ568z_RtM3iLVTAGpaWRwrdgl?usp=sharing)) and also could not reproduce.

**Comment by adriangb** [comment]
I just noticed that that's a warning and not an error. I assume you meant warning?

**Comment by stsievert** [comment]
> I just noticed that that's a warning and not an error. I assume you meant warning? I get the warning under both pytest and python directly.

D'oh. Thanks!

**Comment by adriangb** [comment]
I'll still look into it! SciKeras is definitely manipulating the shapes, it might be unnecessarily converting from (n_samples, ) to (n_samples, 1)

**Comment by stsievert** [comment]
Can I have some help? I can run a Scikit-learn model selection search, but am having a difficult time running a distributed Dask-ML model selection search.

``` python
from dask.distributed import Client
from dask_ml.model_selection import HyperbandSearchCV
if __name__ == "__main__":
    # X, y, model are as above
    client = Client()
    search = IncrementalSearchCV(model2, params, max_iter=5)
    with pytest.warns(DataConversionWarning):
        search.fit(X, y)  # fails on this line
```

When I run this code, I get several errors error: 

1. "TypeError: Expected float32 passed to parameter 'b' of op 'MatMul', got <tf.Variable 'dense_1_2/kernel:0' shape=(512, 10) dtype=float32> of type 'ResourceVariable' instead. Error: 'NoneType' object is not iterable" at tensorflow/python/framework/op_def_library.py", line 475, in _apply_op_helper
2. TypeError: 'NoneType' object is not iterable at tensorflow/python/framework/func_graph.py", line 418, in inner_cm
3. DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel(). at sklearn/utils/validation.py:73: 

Here's the full output:

<details>

```
$  python _scikeras_bug.py
...
/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
2020-07-15 15:07:29.807015: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-15 15:07:29.813243: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-15 15:07:29.818382: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-15 15:07:29.819346: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8a7c1f1fe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-15 15:07:29.819367: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-15 15:07:29.826941: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8b0b201b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-15 15:07:29.826962: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-15 15:07:29.837069: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fdc87b75290 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-15 15:07:29.837096: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
2020-07-15 15:07:29.916084: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
distributed.utils - ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/utils.py", line 656, in log_errors
    yield
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 103, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 547, in partial_fit
    return self.fit(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 511, in fit
    self.model_ = self._build_keras_model(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 304, in _build_keras_model
    model = final_build_fn(**build_args)
  File "_scikeras_bug.py", line 36, in _keras_build_fn
    model = Sequential(layers)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 129, in __init__
    self.add(layer)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 960, in __call__
    self._set_inputs(cast_inputs, outputs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 418, in inner_cm
    for fn in self._scope_exit_callbacks:
TypeError: 'NoneType' object is not iterable
distributed.utils - ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/utils.py", line 656, in log_errors
    yield
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 103, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 547, in partial_fit
    return self.fit(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 511, in fit
    self.model_ = self._build_keras_model(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 304, in _build_keras_model
    model = final_build_fn(**build_args)
  File "_scikeras_bug.py", line 36, in _keras_build_fn
    model = Sequential(layers)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 129, in __init__
    self.add(layer)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 960, in __call__
    self._set_inputs(cast_inputs, outputs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 418, in inner_cm
    for fn in self._scope_exit_callbacks:
TypeError: 'NoneType' object is not iterable
2020-07-15 15:07:29.932341: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb0b125cc00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-15 15:07:29.932392: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function _partial_fit at 0x14b23d550>, (KerasClassifier(
        build_fn=<function _keras_build_fn at 0x14b465160>
        lr=0.0018805049416974935
), {'model_id': 2, 'params': {'lr': 0.0018805049416974935}, 'partial_fit_calls': 0}), array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32), array([4, 0, 2, 1, 3, 8, 5, 0, 3, 1, 2, 7, 9, 1, 3, 4, 7, 7, 1, 8, 6, 3,
       0, 9, 9, 4, 4, 5, 9, 0, 7, 6, 7, 6, 0, 0, 6, 8, 6, 3, 1, 9, 8, 1,
       7, 5, 3, 8, 6, 4, 4, 9, 4, 2, 9, 9, 2, 0, 4, 0, 7, 1, 3, 7, 1, 1,
       6, 3, 1, 2, 8, 6, 5, 2, 4, 7, 9, 9, 0, 8], dtype=uint8), (<class 'dict'>, [])))
kwargs:    {}
Exception: TypeError("'NoneType' object is not iterable")

distributed.utils - ERROR - Expected float32 passed to parameter 'b' of op 'MatMul', got <tf.Variable 'dense_1_2/kernel:0' shape=(512, 10) dtype=float32> of type 'ResourceVariable' instead. Error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 465, in _apply_op_helper
    values = ops.convert_to_tensor(
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1825, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1242, in _dense_var_to_tensor
    return self.value()
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 550, in value
    return self._read_variable_op()
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 645, in _read_variable_op
    result = read_and_set_handle()
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 635, in read_and_set_handle
    result = gen_resource_variable_ops.read_variable_op(self._handle,
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 482, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in _apply_op_helper
    return output_structure, op_def.is_stateful, op, outputs
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 418, in inner_cm
    for fn in self._scope_exit_callbacks:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/utils.py", line 656, in log_errors
    yield
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 103, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 547, in partial_fit
    return selTraceback (most recent call last):
  File "_scikeras_bug.py", line 65, in <module>
    search.fit(X, y)  # fails on this line
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 1006, in fit
f.fit(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 511, in fit
    self.model_ = self._build_keras_model(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 304, in _build_keras_model
    model = final_build_fn(**build_args)
  File "_scikeras_bug.py", line 36, in _keras_build_fn
    model = Sequential(layers)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 129, in __init__
    self.add(layer)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensor    return super(IncrementalSearchCV, self).fit(X, y=y, **fit_params)
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 695, in fit
    return client.sync(self._fit, X, y, **fit_params)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/client.py", line 831, in sync
flow/python/keras/engine/sequential.py", line 213, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1194, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5585, in mat_mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 475, in _apply_op_helper
    raise TypeError(
TypeError: Expected float32 passed to parameter 'b' of op 'MatMul', got <tf.Variable 'dense_1_2/kernel:0' shape=(512, 10) dtype=float32> of type 'ResourceVariable' instead. Error: 'NoneType' object is not iterable
    return sync(
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 641, in _fit
    results = await fit(
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 457, in fit
    return await _fit(
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 253, in _fit
    metas = await client.gather(new_scores)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/distributed/client.py", line 1841, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/scott/Developer/stsievert/dask-ml/dask_ml/model_selection/_incremental.py", line 103, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 547, in partial_fit
    return self.fit(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 511, in fit
    self.model_ = self._build_keras_model(
  File "/Users/scott/Developer/stsievert/scikeras/scikeras/wrappers.py", line 304, in _build_keras_model
    model = final_build_fn(**build_args)
  File "_scikeras_bug.py", line 36, in _keras_build_fn
    model = Sequential(layers)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 129, in __init__
    self.add(layer)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 960, in __call__
    self._set_inputs(cast_inputs, outputs)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/scott/anaconda3/envs/dask-ml-test/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 418, in inner_cm
    for fn in self._scope_exit_callbacks:
TypeError: 'NoneType' object is not iterable
```

</details>

Here's a reproducible example:

<details>

```python
import numpy as np
import pytest
import pickle
from typing import Tuple
from sklearn.exceptions import DataConversionWarning
from dask.distributed import Client

import tensorflow as tf
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.datasets import mnist as keras_mnist
from tensorflow.keras.layers import Activation, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import RandomizedSearchCV
from dask_ml.model_selection import IncrementalSearchCV
from scipy.stats import loguniform


def mnist() -> Tuple[np.ndarray, np.ndarray]:
    (X_train, y_train), _ = keras_mnist.load_data()
    X_train = X_train[:100]
    y_train = y_train[:100]
    X_train = X_train.reshape(X_train.shape[0], 784)
    X_train = X_train.astype("float32")
    X_train /= 255
    Y_train = to_categorical(y_train, 10)
    return X_train, y_train


def _keras_build_fn(lr=0.01):
    layers = [
        Dense(512, input_shape=(784,), activation="relu"),
        Dense(10, input_shape=(512,), activation="softmax"),
    ]
    model = Sequential(layers)

    opt = tf.keras.optimizers.SGD(learning_rate=lr)
    model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
    return model


if __name__ == "__main__":
    X, y = mnist()
    assert X.ndim == 2 and X.shape[-1] == 784
    assert y.ndim == 1 and len(X) == len(y)
    assert isinstance(X, np.ndarray) and isinstance(y, np.ndarray)

    model = KerasClassifier(build_fn=_keras_build_fn, lr=0.1)
    params = {"lr": loguniform(1e-3, 1e-1)}
    model2 = pickle.loads(pickle.dumps(model))

    with pytest.warns(DataConversionWarning):
        m = model.partial_fit(X, y)
    assert m is model

    search = RandomizedSearchCV(model, params, n_iter=3)
    with pytest.warns(DataConversionWarning):
        search.fit(X, y, epochs=2)
    assert search.best_score_ >= 0

    client = Client()
    search = IncrementalSearchCV(model2, params, max_iter=5)
    with pytest.warns(DataConversionWarning):
        search.fit(X, y)  # fails on this line
    assert search.best_score_ >= 0

```

</details>

**Comment by adriangb** [comment]
I'll look into this. It looks like the errors only appear when running through Dask, but not directly? It'll be interesting to see what could cause that.

**Comment by adriangb** [comment]
> 1. "TypeError: Expected float32 passed to parameter 'b' of op 'MatMul', got <tf.Variable 'dense_1_2/kernel:0' shape=(512, 10) dtype=float32> of type 'ResourceVariable' instead. Error: 'NoneType' object is not iterable" at tensorflow/python/framework/op_def_library.py", line 475, in _apply_op_helper
> 2. TypeError: 'NoneType' object is not iterable at tensorflow/python/framework/func_graph.py", line 418, in inner_cm
> 3. DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel(). at sklearn/utils/validation.py:73:

I tested this right now, by cloning your dask branch actually.

I got two types of errors, with no clear reason as to why the alternate.

The first error was at:
```python3
model = Sequential(layers)
```
```
TypeError: 'NoneType' object is not iterable 
```
Strangely, I could solve this by just doing:
```python3
try:
    model = Sequential(layers)
except TypeError:
    model = Sequential(layers)
```

This is very strange and I honestly have no idea what might cause this! It might be worth asking in TF.

The second error was:

```
File "/home/adrian/code/dask-ml/venv/lib/python3.7/site-packages/distributed/utils_test.py", line 954, in test_func
  coro, timeout=timeout * 2 if timeout else timeout
File "/home/adrian/code/dask-ml/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 532, in run_sync
  return future_cell[0].result()
File "/home/adrian/code/dask-ml/venv/lib/python3.7/site-packages/distributed/utils_test.py", line 912, in coro
  result = await future
File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
  raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

I also am not sure what could cause this, but at least it seems like a more reasonable error.

**Comment by adriangb** [comment]
Moved conversation to #24
