### ISSUE TITLE
remove tensorflow dependency

### ISSUE THREAD

**Issue by fcakyon** [adriangb/scikeras#221]
Due to the [tensorflow dependency](https://github.com/adriangb/scikeras/blob/d941d96040e1dda7bf2ae4b9fd861266d90f051b/pyproject.toml#L35), this package is not usable with [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/) package.

Can you please make tensorflow dependency optional so that I can use it with tensorflow-cpu?

**Comment by adriangb** [comment]
Hmm, there's basically no description on the PyPi package (other than some generic `what is TensorFlow` stuff). What is the `tensorflow-cpu` package, and how does it differ from the plain `tensorflow` package? Or can you link me to any relevant docs? Thanks!

**Comment by fcakyon** [comment]
@adriangb It is also maintained by Google and has the same api with tensorflow package. It doesnt include the compiled cuda binaries so that it takes less space and easier to deploy on machines without gpu.

**Comment by fcakyon** [comment]
It is especially useful when deploying an ML app to Heroku: https://stackoverflow.com/a/62356779

**Comment by adriangb** [comment]
Interesting, I sure with the TensorFlow team had better descriptions. Also if they packaged it as an extra like `pip install tensorflow[cpu-only]` 😞 

The main issue with just removing the dependency is that we actually do have minimum TensorFlow versions, and will probably bump them soon. Of course we can replace the requirement with a runtime check, but that has its own disadvantages.

For the time being, it should be possible to install scikeras with `pip install --no-deps scikeras`

**Comment by stsievert** [comment]
> For the time being, it should be possible to install scikeras with pip install --no-deps scikeras

That might be worth adding to the docs.

**Comment by adriangb** [comment]
Agreed, I'll add it in the install section.

**Comment by adriangb** [comment]
@fcakyon I opened #222 to add some guidance in the docs. Do you feel that this would be an acceptable solution?

**Comment by fcakyon** [comment]
@adriangb Unfortunately its not an acceptable solution in my case.

Im using this package in [this web app project](https://github.com/fcakyon/face-recognition-app-tutorial). Heroku creates the environment using [this requirements.txt](https://github.com/fcakyon/face-recognition-app-tutorial/blob/heroku/requirements.txt.

However since scikeras has tensorflow dependency, it downloads both tensorflow-cpu and tensorflow into the environment and [fails the deployment due to limited storage](https://github.com/fcakyon/face-recognition-app-tutorial/deployments/activity_log?environment=face-recognition-api-flask).

Better solution would be to make tensorflow dependency optional: if tensorflow-cpu>2.4.0 is present then dont install tensorflow, else require tensorflow>2.4.0

**Comment by adriangb** [comment]
I see.

It seems that then we are left with two options:
1. Do what you suggested in https://github.com/adriangb/scikeras/issues/221#issue-838138408 and make tensorflow optional so that it would need to be installed via `pip install scikeras[tensorflow]` or `pip install scikeras[tensorflow-cpu]`. However, I think this would be a breaking change, so it would have to wait for a major version.
2. Make a `scikeras-core` package that has no dependencies (only runtime checks). You could then use this `scikeras-core` package and other users could continue to use `scikeras`.

**Comment by fcakyon** [comment]
Would the second approach bring lots of maintenance cost for you? If not, it would be very useful for the ones that are in same situation with me.

**Comment by adriangb** [comment]
It would carry some maintenance burden, I'm not sure how much, but I'll look into it and at least scope it out.

**Comment by stsievert** [comment]
Would [per-requirement overrides][1] work?

[1]:https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides

**Comment by fcakyon** [comment]
@stsievert I tried adding `--install-option="--no-deps"` into [requirements.txt](https://github.com/fcakyon/face-recognition-app-tutorial/blob/b67efa8ba6d7559b0cfee7f85a98913e6a581bc8/requirements.txt#L10) but pip installation fails since pre-requirement commands disable wheel installation. Here is the full heroku deploy log:

```
-----> Building on the Heroku-20 stack
-----> Using buildpacks:
       1. heroku/python
       2. https://github.com/heroku/heroku-buildpack-apt
-----> Python app detected
-----> Stack has changed from heroku-18 to heroku-20, clearing cache
-----> Installing python-3.8.8
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       /app/.heroku/python/lib/python3.8/site-packages/pip/_internal/req/req_file.py:200: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
         cmdoptions.check_install_build_global(options, line.opts)
       Collecting flask==1.1.1
         Downloading Flask-1.1.1.tar.gz (625 kB)
       Collecting gunicorn==19.9.0
         Downloading gunicorn-19.9.0.tar.gz (415 kB)
       Collecting opencv-contrib-python>=4.0
         Downloading opencv-contrib-python-4.5.1.48.tar.gz (148.8 MB)
         Installing build dependencies: started
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: finished with status 'done'
         Getting requirements to build wheel: started
         Getting requirements to build wheel: finished with status 'done'
           Preparing wheel metadata: started
           Preparing wheel metadata: finished with status 'done'
       Collecting matplotlib==3.1.3
         Downloading matplotlib-3.1.3.tar.gz (40.9 MB)
       Collecting imutils==0.5.3
         Downloading imutils-0.5.3.tar.gz (17 kB)
       Collecting requests==2.22.0
         Downloading requests-2.22.0.tar.gz (113 kB)
       Collecting scipy==1.5.4
         Downloading scipy-1.5.4.tar.gz (25.2 MB)
         Installing build dependencies: started
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: still running...
         Installing build dependencies: finished with status 'done'
         Getting requirements to build wheel: started
         Getting requirements to build wheel: finished with status 'done'
           Preparing wheel metadata: started
           Preparing wheel metadata: finished with status 'error'
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python /app/.heroku/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp9jql2k3
                cwd: /tmp/pip-install-iqk9zng4/scipy
           Complete output (171 lines):
           setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-8vvfmt5g'), proceeding with generating Cython sources and expanding templates
             warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
           Running from SciPy source directory.
           lapack_opt_info:
           lapack_mkl_info:
           customize UnixCCompiler
             libraries mkl_rt not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
             NOT AVAILABLE
           
           openblas_lapack_info:
           customize UnixCCompiler
           customize UnixCCompiler
             libraries openblas not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
             NOT AVAILABLE
           
           openblas_clapack_info:
           customize UnixCCompiler
           customize UnixCCompiler
             libraries openblas,lapack not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
             NOT AVAILABLE
           
           flame_info:
           customize UnixCCompiler
             libraries flame not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
             NOT AVAILABLE
           
           atlas_3_10_threads_info:
           Setting PTATLAS=ATLAS
           customize UnixCCompiler
             libraries lapack_atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries tatlas,tatlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries tatlas,tatlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries tatlas,tatlas not found in /usr/lib64
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib
           customize UnixCCompiler
             libraries tatlas,tatlas not found in /usr/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
           customize UnixCCompiler
             libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
           <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
             NOT AVAILABLE
           
           atlas_3_10_info:
           customize UnixCCompiler
             libraries lapack_atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries satlas,satlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries satlas,satlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries satlas,satlas not found in /usr/lib64
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib
           customize UnixCCompiler
             libraries satlas,satlas not found in /usr/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
           customize UnixCCompiler
             libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
           <class 'numpy.distutils.system_info.atlas_3_10_info'>
             NOT AVAILABLE
           
           atlas_threads_info:
           Setting PTATLAS=ATLAS
           customize UnixCCompiler
             libraries lapack_atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries ptf77blas,ptcblas,atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib
           customize UnixCCompiler
             libraries ptf77blas,ptcblas,atlas not found in /usr/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
           customize UnixCCompiler
             libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
           <class 'numpy.distutils.system_info.atlas_threads_info'>
             NOT AVAILABLE
           
           atlas_info:
           customize UnixCCompiler
             libraries lapack_atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries f77blas,cblas,atlas not found in /app/.heroku/python/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries f77blas,cblas,atlas not found in /usr/local/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries f77blas,cblas,atlas not found in /usr/lib64
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib
           customize UnixCCompiler
             libraries f77blas,cblas,atlas not found in /usr/lib
           customize UnixCCompiler
             libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
           customize UnixCCompiler
             libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
           <class 'numpy.distutils.system_info.atlas_info'>
             NOT AVAILABLE
           
           accelerate_info:
             NOT AVAILABLE
           
           lapack_info:
           customize UnixCCompiler
             libraries lapack not found in ['/app/.heroku/python/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
             NOT AVAILABLE
           
           /tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
               Lapack (http://www.netlib.org/lapack/) libraries not found.
               Directories to search for the libraries can be specified in the
               numpy/distutils/site.cfg file (section [lapack]) or by setting
               the LAPACK environment variable.
             if getattr(self, '_calc_info_{}'.format(lapack))():
           lapack_src_info:
             NOT AVAILABLE
           
           /tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
               Lapack (http://www.netlib.org/lapack/) sources not found.
               Directories to search for the sources can be specified in the
               numpy/distutils/site.cfg file (section [lapack_src]) or by setting
               the LAPACK_SRC environment variable.
             if getattr(self, '_calc_info_{}'.format(lapack))():
             NOT AVAILABLE
           
           Traceback (most recent call last):
             File "/app/.heroku/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
               main()
             File "/app/.heroku/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
               json_out['return_val'] = hook(**hook_input['kwargs'])
             File "/app/.heroku/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
               return hook(metadata_directory, config_settings)
             File "/tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
               self.run_setup()
             File "/tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
               super(_BuildMetaLegacyBackend,
             File "/tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
               exec(compile(code, __file__, 'exec'), locals())
             File "setup.py", line 583, in <module>
               setup_package()
             File "setup.py", line 579, in setup_package
               setup(**metadata)
             File "/tmp/pip-build-env-jn9d_eos/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
               config = configuration()
             File "setup.py", line 477, in configuration
               raise NotFoundError(msg)
           numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
           ----------------------------------------
       ERROR: Command errored out with exit status 1: /app/.heroku/python/bin/python /app/.heroku/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp9jql2k3 Check the logs for full command output.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by adriangb** [comment]
Just as a sanity check,  I tried installing `tensorflow` followed by `tensorflow-cpu` to see if having `tensorflow` installed would satisfy the `tensorflow-cpu` dependency or if they would both get installed. They both get installed, which is unfortunate because if `tensorflow` was a superset of `tensorflow-cpu` we could just list `tensorflow-cpu` since SciKeras doesn't do anything specific related to GPU.

**Comment by fcakyon** [comment]
> They both get installed, which is unfortunate 

Yes, indeed. That results in oversized heroku deployment and failure. Trying to find  a way with per-requirement overrides but not successful at the moment.

**Comment by adriangb** [comment]
I think maybe a good next step is to open an issue in tensorflow to look for some guidance. Would you like to do that @fcakyon  or would you prefer I do it?

**Comment by fcakyon** [comment]
I think you could express the situation better then me as a package maintainer. Would you mind opening the issue?

**Comment by adriangb** [comment]
Sure, no problem, I'll tag you.

**Comment by adriangb** [comment]
@fcakyon  I openend https://github.com/tensorflow/tensorflow/issues/48165

**Comment by adriangb** [comment]
It looks like there was already an issue in tensorflow for the same thing: https://github.com/tensorflow/tensorflow/issues/7166

It seems like indeed the move is to make tensorflow an optional dependency. I think we're just going to have to bite the bullet on this one next major version bump @stsievert

**Comment by stsievert** [comment]
What do you "bite the bullet"?

**Comment by adriangb** [comment]
Sorry, I should have been clearer.

Accept that we will need to make a backwards incompatible change that has its own set of downsides.

**Comment by stsievert** [comment]
[Semantic versioning][1] lays out the following:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> *MAJOR version when you make incompatible API changes,
> * MINOR version when you add functionality in a backwards compatible manner, and
> * PATCH version when you make backwards compatible bug fixes.

So sounds like the minor version should be bumped from 0.2.1 to 0.3.0.

[1]:https://semver.org/

**Comment by adriangb** [comment]
Ugh sorry yes, you are right, spaghetti in my brain. I meant minor. So what you are saying is spot on.

**Comment by fcakyon** [comment]
@adriangb thats great news!

**Comment by adriangb** [comment]
Yep! Just decided to bite the bullet on it... If you can test off of `master` and confirm this fixes things for you, that'd be much appreciated!
