### ISSUE TITLE
Estimator definition for Dask HyperbandSearchCV

### ISSUE THREAD

**Issue by sim-san** [adriangb/scikeras#31]
Hi Adrian,
thanks for developing and helping with scikeras.

I made this example code (https://github.com/adriangb/scikeras/issues/24#issuecomment-666480764) run on my PC.
But I still have a question respectively a problem.

There are 3 waysof creating a dynamically built model:

**1. Passing a callable function**
`model = KerasRegressor(build_fn=model_building_function, hidden_layer_sizes=[32, 32], activation_func="relu")`
This **works** with the given example

<details><summary>Code</summary>
<p>

```python
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from scikeras.wrappers import KerasRegressor

import numpy as np
from dask.distributed import Client, LocalCluster

import dask_ml.model_selection as dcv


def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    """Dynamically build regressor."""

    model = Sequential()
    model.add(Flatten(input_shape=X.shape[1:]))
    for size in hidden_layer_sizes:
        model.add(Dense(size, activation=activation_func))
    model.add(Dense(n_outputs_))
    model.compile("adam", loss="mean_squared_error")
    return model


class Est(KerasRegressor):
    def __init__(self, hidden_layer_sizes=None, activation_func=None):
        self.hidden_layer_sizes = hidden_layer_sizes
        self.activation_func = activation_func
        super().__init__()

    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model


if __name__ == "__main__":
    cluster = LocalCluster(processes=True, n_workers=5, threads_per_worker=1)
    #  cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=1)

    dask_client = Client(cluster)

    model = KerasRegressor(build_fn=model_building_function, hidden_layer_sizes=[32, 32], activation_func="relu")
    #  model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")
    #  model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")

    # generate data
    X = np.arange(1.0, 5001.0).reshape((100, 50)).astype(np.float32)
    y = np.arange(1.0, 101.0).reshape(100, 1).astype(np.float32)

    # specify parameters and distributions to sample from
    param_dist = {
        "hidden_layer_sizes": [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256]],
        "activation_func": ["relu", "elu"],
    }

    hyperband = dcv.HyperbandSearchCV(model, param_dist, max_iter=12)

    print("START HyperbandSearchCV")
    hyperband.fit(X, y)
    print("best score =", hyperband.best_score_)
    assert hasattr(hyperband, "best_score_")
```

</p>
</details>

**2. Instance of a class implementing __call__ as the build_fn parameter**
`model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")`
This **works** with the given example.

<details><summary>Code</summary>
<p>

```python
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from scikeras.wrappers import KerasRegressor

import numpy as np
from dask.distributed import Client, LocalCluster

import dask_ml.model_selection as dcv


def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    """Dynamically build regressor."""

    model = Sequential()
    model.add(Flatten(input_shape=X.shape[1:]))
    for size in hidden_layer_sizes:
        model.add(Dense(size, activation=activation_func))
    model.add(Dense(n_outputs_))
    model.compile("adam", loss="mean_squared_error")
    return model


class Est(KerasRegressor):
    def __init__(self, hidden_layer_sizes=None, activation_func=None):
        self.hidden_layer_sizes = hidden_layer_sizes
        self.activation_func = activation_func
        super().__init__()

    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model


if __name__ == "__main__":
    cluster = LocalCluster(processes=True, n_workers=5, threads_per_worker=1)
    #  cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=1)

    dask_client = Client(cluster)

    #  model = KerasRegressor(build_fn=model_building_function, hidden_layer_sizes=[32, 32], activation_func="relu")
    model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")
    #  model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")

    # generate data
    X = np.arange(1.0, 5001.0).reshape((100, 50)).astype(np.float32)
    y = np.arange(1.0, 101.0).reshape(100, 1).astype(np.float32)

    # specify parameters and distributions to sample from
    param_dist = {
        "hidden_layer_sizes": [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256]],
        "activation_func": ["relu", "elu"],
    }

    hyperband = dcv.HyperbandSearchCV(model, param_dist, max_iter=12)

    print("START HyperbandSearchCV")
    hyperband.fit(X, y)
    print("best score =", hyperband.best_score_)
    assert hasattr(hyperband, "best_score_")
```

</p>
</details>

**3. Subclass the wrapper and implement __call__ in your class.**
`model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")`
This **does not work** with the given example. 

<details><summary>Code</summary>
<p>

```python
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from scikeras.wrappers import KerasRegressor

import numpy as np
from dask.distributed import Client, LocalCluster

import dask_ml.model_selection as dcv


def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    """Dynamically build regressor."""

    model = Sequential()
    model.add(Flatten(input_shape=X.shape[1:]))
    for size in hidden_layer_sizes:
        model.add(Dense(size, activation=activation_func))
    model.add(Dense(n_outputs_))
    model.compile("adam", loss="mean_squared_error")
    return model


class Est(KerasRegressor):
    def __init__(self, hidden_layer_sizes=None, activation_func=None):
        self.hidden_layer_sizes = hidden_layer_sizes
        self.activation_func = activation_func
        super().__init__()

    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model


if __name__ == "__main__":
    cluster = LocalCluster(processes=True, n_workers=5, threads_per_worker=1)
    #  cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=1)

    dask_client = Client(cluster)


    #  model = KerasRegressor(build_fn=model_building_function, hidden_layer_sizes=[32, 32], activation_func="relu")
    #  model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")
    model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")

    # generate data
    X = np.arange(1.0, 5001.0).reshape((100, 50)).astype(np.float32)
    y = np.arange(1.0, 101.0).reshape(100, 1).astype(np.float32)

    # specify parameters and distributions to sample from
    param_dist = {
        "hidden_layer_sizes": [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256]],
        "activation_func": ["relu", "elu"],
    }

    hyperband = dcv.HyperbandSearchCV(model, param_dist, max_iter=12)

    print("START HyperbandSearchCV")
    hyperband.fit(X, y)
    print("best score =", hyperband.best_score_)
    assert hasattr(hyperband, "best_score_")
```

</p>
</details>

I got the following error: 
`TypeError: __call__() missing 3 required positional arguments: 'n_outputs_', 'hidden_layer_sizes', and 'activation_func`

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/optimization_library/tests/testing.py", line 82, in <module>
    hyperband.fit(X, y)
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\dask_ml\model_selection\_incremental.py", line 702, in fit
    return client.sync(self._fit, X, y, **fit_params)
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\distributed\client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\distributed\utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\distributed\utils.py", line 332, in f
    result[0] = yield future
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\dask_ml\model_selection\_hyperband.py", line 402, in _fit
    *[SHAs[b]._fit(X, y, **fit_params) for b in _brackets_ids]
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\dask_ml\model_selection\_incremental.py", line 660, in _fit
    prefix=self.prefix,
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\dask_ml\model_selection\_incremental.py", line 478, in fit
    prefix=prefix,
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\dask_ml\model_selection\_incremental.py", line 262, in _fit
    metas = await client.gather(new_scores)
  File "D:\PycharmProjects\optimization_library\venv_dask_hyperband\lib\site-packages\distributed\client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
TypeError: __call__() missing 3 required positional arguments: 'n_outputs_', 'hidden_layer_sizes', and 'activation_func'
```

</p>
</details>

<details><summary>dask error</summary>
<p>

```
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function _partial_fit at 0x00000233830B81F8>, (Est(
	activation_func=elu
	hidden_layer_sizes=[128, 128]
), {'model_id': 1, 'params': {'hidden_layer_sizes': [128, 128], 'activation_func': 'elu'}, 'partial_fit_calls': 0}), array([[3301., 3302., 3303., ..., 3348., 3349., 3350.],
       [4451., 4452., 4453., ..., 4498., 4499., 4500.],
       [ 851.,  852.,  853., ...,  898.,  899.,  900.],
       ...,
       [2051., 2052., 2053., ..., 2098., 2099., 2100.],
       [  51.,   52.,   53., ...,   98.,   99.,  100.],
       [4851., 4852., 4853., ..., 4898., 4899., 4900.]], dtype=float32), array([[ 67.],
       [ 90.],
       [ 18.],
       [ 95.],
       [  5.],
       [ 23.],
       [100.],
       [ 82.],
       [ 48.],
       [ 76.],
       [ 57.],
       [ 36.],
       [ 77.],
       [ 47.],
       [ 94.],
       [ 19.],
       [ 27.],
       [ 80.],
       [  9.],
       [ 33.],
       [ 88.],
       [ 28.],
       [ 66.],
       [ 40.],
       [ 50.],
       [ 55.],
       [ 25.],
      
kwargs:    {}
Exception: TypeError("__call__() missing 3 required positional arguments: 'n_outputs_', 'hidden_layer_sizes', and 'activation_func'")
```

</p>
</details>

Thanks for help.

**Comment by adriangb** [comment]
Hi, can you post a complete example please? Thanks!

**Comment by sim-san** [comment]
I updated my first comment https://github.com/adriangb/scikeras/issues/31#issue-669874356

**Comment by adriangb** [comment]
Hmm this is interesting. I was able to reproduce this. So obviously somewhere within Dask `model ` is getting called directly (i.e. `model()`). I'm having trouble tracking down where because of the complexity of the internals and my unfamiliarity with them.

Generally, I feel that using `__call__` like this package does is not great, and this would never happen if the function was called `build_kears_model_` instead or something like that.

@stsievert do you have any insight?

**Comment by stsievert** [comment]
Dask-ML's model selection does the equivalent of this code:

``` python
from sklearn.linear_model import SGDClassifier
from scipy.stats import uniform
from sklearn.model_selection import ParameterSampler
from sklearn.base import clone

# User-specified
param_space = {"alpha": uniform(0, 1)}
user_model = SGDClassifier()

# Inside Dask-ML
params = list(ParameterSampler(param_space, n_iter=1))[0]
model_to_tune = clone(user_model).set_params(**params)
```

The relevant code is at [dask_ml/model_selection/_incremental.py#L129-L132][1]. It looks like the model on [_incremental.py#L137][2] is the user-defined model passed to `HyperbandSearchCV`.

[2]:https://github.com/dask/dask-ml/blob/master/dask_ml/model_selection/_incremental.py#L137

[1]:https://github.com/dask/dask-ml/blob/5c3179eb7eaa6bf830e0b6df162902f805a9b3c0/dask_ml/model_selection/_incremental.py#L129-L132

**Comment by adriangb** [comment]
Right, the part I'm not understanding is where/why Dask calls `model()` triggering the call of `model.__call__()` with no args.

**Comment by stsievert** [comment]
The code does perform `deepcopy(model)` on every `partial_fit` call. Could that be responsible? I'm not seeing anything else.

Why is this an issue? 2 out of 3 methods in https://github.com/adriangb/scikeras/issues/31#issue-669874356. of initializing the `KerasRegressor` work with Dask.

**Comment by adriangb** [comment]
`deepcopy` should work fine. It's not a huge issue since like you say there are ways around it, but it would be nice to at least know why this is happening. Maybe it's good enough reason to justify a switch from `__call__`  to `build_keras_model_` or something less likely to be accidentally called.

**Comment by sim-san** [comment]
@adriangb should I report further problems I encounter between scikeras and dask-ml here or at the repo of dask-ml ?

**Comment by adriangb** [comment]
Please do continue to report them here. I think this is (1) a smaller more nimble project and (2) more likely to be the source of the bugs/bad design.

Regarding this issue specifically, I'm going to look into changing the name of the function for subclassed wrappers from `__call__` to something else. I think the change should be backward compatible with the original wrappers from TF (I'm okay with breaking my own API, but not backward compatibility with the old API, at least for now) but I have to double check and implement/test.

**Comment by stsievert** [comment]
> Please do continue to report them here. 

I also think that's best: Dask-ML doesn't have any code related to SciKeras. But please ping me and/or @TomAugspurger.

**Comment by adriangb** [comment]
I was able to confirm that renaming `__call__` fixed the issue. I still don't understand why `__call__` was being called, but I'm guessing Daks is introspecting somewhere and the fact that the class instance is a callable triggers some logic. I think this is evidence that it was a bad design decision to use `__call__`  in the first place. I opened #35 to implement this change, if you can confirm that the branch in #35 fixes this for you that would be great @sim-san. Thank you for reporting this!

**Comment by sim-san** [comment]
Thanks for the fast solution. I will test it tomorrow

**Comment by adriangb** [comment]
@sim-san sorry I closed #35 without seeing your edit! Let me check real quick, I'll revert the commit if needed.

**Comment by adriangb** [comment]
I think there may be some confusion regarding the APIs (please let me know if I am misunderstanding). The three APIs should be:

#### 1. `build_fn` is a callable function (did not change)
```python3
def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    model = Sequential()
    ...
    return model

model = KerasRegressor(build_fn=model_building_function)
```

#### 2. `build_fn` is a callable class (did not change)

```python3
class MyClass:

   def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
      model = Sequential()
    ...
    return model

model = KerasRegressor(build_fn=model_building_function)
```

#### 3.  Subclassing **(did change)**
```python3
class MyClass(KerasRegressor):

   def _keras_build_fn(self, X, n_outputs_, hidden_layer_sizes, activation_func):
      model = Sequential()
    ...
    return model

model = MyClass()
```

**Comment by sim-san** [comment]
ok. Now I understand how to use the callable class.In the previous version it was also possible to use the class " Subclassing" as a callable class. The change to the "_keras_build_fn" for subclassing does not allow this anymore.

I think we need some more changes in the Readme.md (L126 and 164):

L136: __call__(...) => _keras_build_fn(...)
L156: __call__(...) => _keras_build_fn(...)

```python3
from scikeras.wrappers import KerasRegressor


class MLPRegressor(KerasRegressor):

    def __init__(self, hidden_layer_sizes=None, **kwargs):
        self.hidden_layer_sizes = hidden_layer_sizes
        super().__init__(**kwargs)   # this is very important!

    def _keras_build_fn(self, X, n_outputs_, hidden_layer_sizes):
        ...

estimator = MLPRegressor(hidden_layer_sizes=[200], a_kwarg="saveme")

estimator.a_kwarg == "saveme"  # True
```

This interface allows for multiple layers of inheritence and consumption of arguments:

```python3
from scikeras.wrappers import KerasRegressor


class ChildMLPRegressor(MLPRegressor):

    def __init__(self, child_argument=None, **kwargs):
        self.child_argument = child_argument
        super().__init__(**kwargs)   # this is very important!

    def _keras_build_fn(self, X, n_outputs_, hidden_layer_sizes):
        ...

estimator = ChildMLPRegressor(child_argument="hello", a_kwarg="saveme")

estimator.child_argument == "hello"  # True
estimator.a_kwarg == "saveme"  # True
estimator.hidden_layer_sizes == None  # True, the default in MLPRegressor is used
```

**Comment by adriangb** [comment]
Agreed! Must have missed that in #35
